name: ImageBuild
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image
      run: |
        docker build . -t test
    - name: Run test
      run: |
        docker run --rm test bash -c './deep_simulator.sh -i example/001c577a-a502-43ef-926a-b883f94d157b.true_fasta -n -1 -B 2 '
        ls ./